### ISSUE TITLE
KeyError: (0, 1, 1, 0, 0, 0, 1)

### ISSUE THREAD

**Issue by mansi733** [onlyphantom/cvessentials#12]
While running the code either predicts wrong values or gets a key error whenever giving a new image, and also not able to read decimal values.
Key Error -
![key error](https://user-images.githubusercontent.com/82514056/202997729-b75890a7-89e4-4f1c-81ab-b96ca46257ed.PNG)
Wrong output-
![wrongop](https://user-images.githubusercontent.com/82514056/202998370-09d1bebf-3aab-457f-8d06-eb28c53a9c0f.png)
can you please help me with this issue?
Thank you.

**Comment by onlyphantom** [comment]
Hi @mansi733 , this repository is meant for educational purposes and some of the parameters are hard-coded to fit the dataset supplied in the course. If you're using a dataset outside of the ones provided, you will need to change these parameters to tailor fit your own use-cases.

Take a look at [digit_01.py](https://github.com/onlyphantom/cvessentials/blob/master/digitrecognition/digit_01.py) and work your modifications in. For one, given how "tall" each characters are, you should try to print `sevensegs` (line 114) and check that you got those individual segments done right. Most likely you'll need to modify the proportion (`0.25` and `0.15`) on line 110 and line 111 as well. 

Good luck!

**Comment by mansi733** [comment]
@onlyphantom Thank you. But what about the key error? Do I need to change anything in the dictionary(DIGITSDICT)?
